sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tFNaPMPYuRWyP6D6nH8
    accessKeySecret: 2yUVmdScfgMyHvDGdClO6xEQJ3rcVI
    bucketName: sky-waimai23
  Redis:
    host: localhost
    port: 6379
    auth: 1234
    database: 0
  wechat:
    appid: wxfce0ac6b2efc8d0c
    secret: e78924f7bb45402e82520c35c7bf1a8a